directories:
  output: dist_electron
  buildResources: build
appId: com.mssakib.glyphforge
productName: GlyphForge
copyright: Copyright Â© 2025 MS Sakib
win:
  target:
    - portable
  icon: public/vite.svg
files:
  - filter:
      - dist/**/*
      - main.js
      - package.json
electronVersion: 39.2.7
